server:
  port: 8080
spring:
  application:
    name:
      multiple-data-sources
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      # spring中使用jdbc连接数据库时，url要写成jdbc-url
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: 123456
    sqlserver:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=Test2;encrypt=false;trustServerCertificate=false;
      username: sa
      password: 123456

mybatis:
#  mapper-locations:
#    - classpath:mapper/ms/*.xml
#    - classpath:mapper/mysql/*.xml
#  type-aliases-package: com.zyl.multiple.data.sources.pojo
#  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#logging:
#  level:
#    org.apache.ibatis: DEBUG
#    com.example.mapper: DEBUG


